# Generated by Django 5.0 on 2024-04-13 14:18

import common.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', common.mixins.TruncatingCharField(max_length=150)),
                ('trading_name', common.mixins.TruncatingCharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, common.mixins.TruncateCharFieldsMixin),
        ),
    ]
