# Generated by Django 5.0.6 on 2024-07-01 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authService', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
